#!/usr/bin/env ruby

require "open-uri"
require "json"

class PinboardCollection
  def self.call
    new.call
  end

  def call
    auth_token = ENV["PINBOARD_AUTH_TOKEN"]
    url = "https://api.pinboard.in/v1/posts/all?tag=danott.co&format=json&auth_token=#{auth_token}"
    JSON.load(strip_byte_order_mark(URI.open(url).read))
  end

  private

  def strip_byte_order_mark(potentially_unparsable)
    potentially_unparsable.dup.sub("\xEF\xBB\xBF".force_encoding("UTF-8"), "")
  end
end

class EleventyFormatter
  def self.call(pinboard_collection)
    pinboard_collection.map { |pinboard_record| new(pinboard_record).call }
  end

  attr_reader :pinboard_record

  def initialize(pinboard_record)
    @pinboard_record = pinboard_record
  end

  def call
    {
      commentary: pinboard_record.fetch("extended"),
      date: pinboard_record.fetch("time"),
      hash: pinboard_record.fetch("hash"),
      tags: tags,
      title: pinboard_record.fetch("description"),
      url: pinboard_record.fetch("href"),
    }
  end

  private

  def tags
    pinboard_record.fetch("tags").split(" ") - ["danott.co"]
  end
end

json = EleventyFormatter.call(PinboardCollection.call)
puts JSON.dump(json)
